### ISSUE TITLE
Postman example of how to consume the API endpoints locally

### ISSUE THREAD

**Issue by MartinCalderon-x** [Jonyx4/node-express-mongo-oauth#6]
Add a Postman example of how to consume the API endpoints locally including oauth (This will require that we create a record on the oauth collection first and that we know the user and key)

**Comment by agustin-pcscom** [comment]
[node-express-mongo-oauth.postman_collection.json.zip](https://github.com/Jonyx4/node-express-mongo-oauth/files/9862926/node-express-mongo-oauth.postman_collection.json.zip)

**Comment by agustin-pcscom** [comment]
Se adjunta collection.
